# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import videoapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=455)),
                ('public_access', models.BooleanField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_duration', models.CharField(max_length=6)),
                ('author', models.ForeignKey(on_delete=models.SET(videoapp.models.get_ghost_user), to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Videos')),
            ],
        ),
    ]
