# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=models.SET(main.models.get_ghost_user), to=settings.AUTH_USER_MODEL)),
                ('video_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoapp.VideoPost')),
            ],
        ),
    ]
