# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_number', models.IntegerField()),
                ('word_to_url', models.URLField()),
                ('word_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BlobStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_name', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PipelineTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.IntegerField()),
                ('segment_duration', models.FloatField()),
                ('audio_blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BlobStorage')),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_index', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Transcripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('segment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Segments')),
            ],
        ),
        migrations.CreateModel(
            name='Utterances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance_index', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('transcript_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transcripts')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('finished_processing', models.BooleanField()),
                ('processing_status', models.CharField(max_length=20)),
                ('video_duration', models.FloatField(default=-1.0)),
                ('audio_blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_path', to='main.BlobStorage')),
                ('pipeline_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PipelineTypes')),
                ('video_blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_path', to='main.BlobStorage')),
            ],
        ),
        migrations.AddField(
            model_name='transcripts',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Videos'),
        ),
        migrations.AddField(
            model_name='tokens',
            name='utterance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Utterances'),
        ),
        migrations.AddField(
            model_name='segments',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Videos'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='segment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Segments'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Videos'),
        ),
    ]
