# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='processing_status',
            field=models.CharField(max_length=50),
        ),
    ]
