# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('image_blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BlobStorage')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Videos')),
            ],
        ),
    ]
